meta_product_name: "Local"
meta_title: "Local - To Find Culture, Go Local."
meta_description: "Travel authentically anywhere in the world with the best experiences curated by Locals."
meta_image: "new-logo-local-small.jpg" # should exist in `app/assets/images/`
